tone_tracker/config/routes.rb
Rails.application.routes.draw do

  root 'application#index'

  resources :users, only: [:new, :create, :show]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

end

tone_tracker/app/models/content.rb
class Content < ActiveRecord::Base
  validates :body, presence: true

  belongs_to :user
  has_many :emotions
  has_many :languages
  has_many :tendencies

end

tone_tracker/app/models/emotion.rb
class Emotion < ActiveRecord::Base
  validates :name, :score, presence: true

  belongs_to :content
end

tone_tracker/app/models/language.rb
class Language < ActiveRecord::Base
  validates :name, :score, presence: true

  belongs_to :content
end

tone_tracker/app/models/tendency.rb
class Tendency < ActiveRecord::Base
  validates :name, :score, presence: true

  belongs_to :content
end

tone_tracker/app/models/user.rb
class User < ActiveRecord::Base

validates :username, :email, :password, presence: true

has_secure_password

has_many :contents
has_many :emotions, through: :contents
has_many :languages, through: :contents
has_many :tendencies, through: :contents

end

tone_tracker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def index
  end
end

tone_tracker/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if logged_in?
      redirect_to root_path
    else
      @user = User.new
    end
  end

  def create
    @user = User.find_by(login_username)
    if @user && @user.authenticate(login_password[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      if @user
        @user.errors[:password].push("incorrect")
      else
        @user = User.new
        @user.errors[:username].push("not found")
      end
      render 'new'
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  private
  def login_username
    params.require(:login).permit(:username)
  end

  def login_password
    params.require(:login).permit(:password)
  end
end

tone_tracker/app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    if logged_in?
      redirect_to root_path
    else
      @user = User.new
    end
  end

  def create
  end

  def show
  end
end

tone_tracker/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    if logged_in?
      redirect_to root_path
    else
      @user = User.new
    end
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

tone_tracker/app/helpers/application_helper.rb
module ApplicationHelper
end

tone_tracker/app/helpers/sessions_helper.rb
module SessionsHelper
end

tone_tracker/app/helpers/user_helper.rb
module UserHelper
end

tone_tracker/app/views/application/index.html.erb
<h1>Welcome to Tone Tracker!</h1>

tone_tracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToneTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= link_to "Home", root_path%>
  <% if logged_in? %>
    <%= link_to "Profile", user_path(current_user) %>
    <%= link_to "Logout", logout_path %>
  <% else %>
    <%= link_to "Register", new_user_path %>
    <%= link_to "Login", login_path %>
  <% end %>

<%= yield %>

</body>
</html>

tone_tracker/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  The form contains <%= pluralize(object.errors.count, "error") %>.
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
<% end %>

tone_tracker/app/views/users/new.html.erb
<h1>Register as a new user</h1>

<%= render partial: 'shared/error_messages', locals: { object: @user } %>

<%= form_for :user, url: { action: "create" } do |f| %>

  <%= f.label :username %>
  <%= f.text_field :username %>
  <br>

  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>

  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>

  <%= f.submit "Register" %>

<% end %>

tone_tracker/app/views/users/show.html.erb
<h1><%= @user.username %>'s Profile</h1>

<p>Will show all content that has been run through IBM tone analysis</p>